### ISSUE TITLE
Unable to use exam schema 0.3 with exam engine

### ISSUE THREAD

**Issue by teroz** [digabi/exam-engine#1567]
Hi there. I installed exam engine latest version `16.0.3`, created a new exam as per the README. This generates an exam schema that's in version 0.2. 

I am able to upgrade the schema to version 0.3 successfully with the `ee migrate`. As soon as I try and preview this new upgraded exam the engine falls over - could you kindly have a look 

![Screenshot from 2021-07-12 10-46-43](https://user-images.githubusercontent.com/853846/125250172-3ab98100-e2f6-11eb-948f-d67781adb776.png)

**Comment by sluukkonen** [comment]
I believe this has been fixed.
