### ISSUE TITLE
Where's the MEB file extension documentation?

### ISSUE THREAD

**Issue by developerfromjokela** [digabi/exam-engine#443]
Hello,

README mentions something about MEF fileformat's documentation. Where is it?

**Comment by sluukkonen** [comment]
The packaged  MEB and MEX file formats aren't really documented right now, since only YTL can sign them with a private key that Abitti respects. 

Documentation about the exam XML structure can be found from https://digabi.github.io/exam-engine/MexDocumentation/

**Comment by developerfromjokela** [comment]
What about reading them? There's one reason why it should be documented at least for decoding it.

**Comment by developerfromjokela** [comment]
Is the Abitti's private key involved in the reading process? Doesn't it encrypt using the "random" key?
