### ISSUE TITLE
Do annotations render correctly in the <Results /> component?

### ISSUE THREAD

**Issue by Zloka** [digabi/exam-engine#640]
Currently, in my testing, I've set a few `annotations` for my `pregrading` score. They are simple enough:

```
{
  startIndex: 0,
  length: 3,
  message: 'ab',
}
```

Are these rendered correctly? The annotations show up below the comment, but there is no indication in the student's answer to _which part of the answer_ each annotation corresponds to (see image below).
![image](https://user-images.githubusercontent.com/17513212/87977526-8ec0c980-cad7-11ea-9175-7ca6eac09d71.png)

**Comment by sluukkonen** [comment]
At the moment, annotations aren't actually rendered by exam-engine. We use a (fairly crude) [separate library](https://github.com/digabi/answer-annotation/) for rendering them.

We do basically something like the following:

```javascript
const annotationsRendering = require('@digabi/answer-annotation/dist/annotations-rendering')

ReactDOM.render(<Results {...props} />, document.getElementById('app'), () => {
  $('[data-pregrading-annotations],[data-censoring-annotations]').each(
    (i, el) => {
      const $el = $(el)
        annotationsRendering.renderInitialAnnotationsForElement(
          $el,
          $el.data('pregrading-annotations'),
          $el.data('censoring-annotations')
        )

    }
  )
})
```

Rendering annotations with exam-engine and cleaning up the API has been in the talks, but nothing concrete yet.

**Comment by Zloka** [comment]
Alrighty, gonna give that a try. I would imagine this works well for text, but what about images (mainly the formulas created using the rich text editor)? :)

**Comment by sluukkonen** [comment]
The answer-annotation library handles both text and image annotations.

**Comment by sluukkonen** [comment]
@Zloka We're now working on rendering annotations in exam-engine. The aim is to use this code in the matriculation exams this fall.

PR here, if you're interested: https://github.com/digabi/exam-engine/pull/727

**Comment by Zloka** [comment]
Interesting, thanks for letting me know! We went ahead and used the separate library per your instructions, but this would allow us to clean up our code quite a bit! :)

**Comment by sluukkonen** [comment]
Version 14.0.0 has now been released, and it includes the new annotation rendering code. Let me know if you guys find any issues.
