### ISSUE TITLE
Runnable in a container?

### ISSUE THREAD

**Issue by kinnala** [digabi/exam-engine#743]
Can exam-engine be run in a container?

I tried the following:
```
[tom@tunkki:~]$ docker run -it ubuntu /bin/bash
root@bd83d61dcb08:/# apt-get upgrade
root@bd83d61dcb08:/# apt-get install nodejs npm
root@bd83d61dcb08:/# npm install -g @digabi/exam-engine-cli
root@bd83d61dcb08:/# ee new testi
root@bd83d61dcb08:/# ee create-offline testi
✖ Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/build/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/build/Release/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/Debug/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/out/Release/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/Release/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/build/default/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/compiled/10.19.0/linux/x64/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/addon-build/release/install-root/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/addon-build/debug/install-root/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/addon-build/default/install-root/xmljs.node
 → /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/lib/binding/node-v64-linux-x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/index.js:4:18)
```
I'm no javascript expert, so this might be something obvious.

**Comment by sluukkonen** [comment]
Which version of Node.js are you using?

**Comment by sluukkonen** [comment]
For some reason, one of our dependencies doesn't seem to install properly when installed as root.

I was able to fix this in my test container with `cd /usr/local/lib/node_modules/@digabi/exam-engine-cli && npm rebuild libxmljs2`

**Comment by kinnala** [comment]
Thanks! With this Dockerfile everything else but `create-offline` seems to work:
```
FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y nodejs npm firefox
ENV PUPPETEER_PRODUCT=firefox
RUN npm --verbose install -g @digabi/exam-engine-cli; exit 0
RUN cd /usr/local/lib/node_modules/@digabi/exam-engine-cli && npm rebuild libxmljs2
```
For `create-offline` I get:
```
root@91deb9d4ae5b:/# ee create-offline test
✖ Error: Could not find browser revision latest. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:219:23)
```
I tried adding the above suggestions as environment variables but it didn't help.

**Comment by kinnala** [comment]
Another challenge is that when I run `preview` the port seems to be chosen randomly:
```
root@14fa0243a2b1:/# ee preview test
ℹ Server is running at http://localhost:38523
✔ Press Ctrl-C to stop
...
root@d5dae5f944d7:/# ee preview test
ℹ Server is running at http://localhost:41715
✔ Press Ctrl-C to stop
```
Thus it's challenging to open a specific port to the container. Maybe there is/should be an option to fix the port?

**Comment by kinnala** [comment]
It seems that the port randomization is caused by this line: https://github.com/digabi/exam-engine/blob/master/packages/rendering/src/getPreviewWebpackConfig.ts#L42

**Comment by kinnala** [comment]
Made a rough attempt on adding a port flag to the CLI in #763, but as mentioned in the PR, I have no idea what I'm doing.

**Comment by sluukkonen** [comment]
Some points:

I suspect the current problems with create-offline are related to root account as well. The error message indicates that Puppeteer didn't install correctly. Could you try installing exam-engine with a normal user and see if it helps?

The port is chosen randomly by design -- our users often times preview multiple exams at once, so hardcoding port by default is a no-go. 

Adding an option for fixing the port seems like a fine feature though.

**Comment by sluukkonen** [comment]
Also, we are using Chrome in puppeteer, so I don't think you should set the `ENV PUPPETEER_PRODUCT` environment variable. We are using Chrome with Puppeteer, so adding the `ENV PUPPETEER_PRODUCT=firefox` bit will just further confuse npm.

**Comment by kinnala** [comment]
Alright, that makes sense. Do you think this part of the README needs info about Chrome? https://github.com/digabi/exam-engine#setup

**Comment by sluukkonen** [comment]
Puppeteer should handle the installation of Chrome (or Firefox, if you set the environment variable) automatically, so I don't think it's necessarily worth mentioning. 

I think that in your case the installation just fails for whatever reason. Perhaps because its installation script isn't designed to run with root?

**Comment by kinnala** [comment]
I'll try the installation on a non-root user and report the results in a bit. Thanks for support.

**Comment by sluukkonen** [comment]
You should be able to configure NPM to install packages in the current user's home directory with something like 

```
$ npm config set prefix ~/.npm
```

I think that NPM installed from Ubuntu repositories is configured differently for some reason.

See e.g. https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92 for more information.

**Comment by sluukkonen** [comment]
As a side note, perhaps one of the official Node docker images would be a better starting point. At the very least, their version of Node isn't as ancient as in the official Ubuntu repositories.

**Comment by kinnala** [comment]
> As a side note, perhaps one of the official Node docker images would be a better starting point.

Good idea, I'll try that out.
